import { Inter } from "next/font/google";
import "./globals.css";

import Sidebar from "@/components/menubar/menubar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Controle Financeiro",
  description: "Generated by Pedro Virgilio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
